Use gulp to start the pattern lab server and watch for changes
nerdstein/nerdstein-design-library pull request #23
Opened 2017-06-10 16:00 UTC by daggerhart

This addresses #22 

Changes:

* New `gulp-shell` module.
* New `gulp-shell` task for starting the pattern lab server
* Pattern lab server task added to the default gulp task
* Updated readme to reflect the simplified developer workflow
* Removed an old version of `list-element.json` which was causing a PHP warning during pattern lab compilation. 

One more thing: I'm not sure why exactly, but when I run this task the compiled css file changes the order of the `h3.list-title` and `div.list-body`. There doesn't appear to be a difference in the output for these elements, just their order has changed (see below). 

![new-css-order](https://user-images.githubusercontent.com/1205329/27004216-9fddc648-4dd3-11e7-90ac-65bf79d3e89d.png)

I don't think this should have been an effect of my changes, but since it is the result after my changes I've included it in this PR.

Thoughts/feedback welcome

2017-06-13 13:59 UTC, nerdstein requested changes
This looks great and I love the enhancement.

I'm not sure why the one file is being removed though. Can you take a look?

2017-06-13 13:59 UTC, nerdstein commented on design-library/source/_patterns/02-molecules/02-list-element/list-element~1.json
> -{
I'm curious why this file is deleted. It probably should be there to show the second list element

2017-06-13 15:42 UTC, daggerhart commented
This maybe a misunderstanding of patternlab, but I deleted that file because I was getting PHP warnings during generation.  

(Like this, but not exactly. This is the warning I just got while testing #24)
![screen shot 2017-06-13 at 11 32 21 am](https://user-images.githubusercontent.com/1205329/27090729-01f12898-502c-11e7-96a9-5dff7a960dba.png)

I googled around for that error but didn't find anything, so tracked that down to `PatternLab\PatternData\Rule::getPatternName`. Found that patternlab was getting confused about the filename `list-element~1.json` and interpreting by looking for a item named "1". 

(var_dump FTW)
![screen shot 2017-06-13 at 11 37 36 am](https://user-images.githubusercontent.com/1205329/27090968-bc6d42ba-502c-11e7-88d4-45a78a6c91ba.png)

Deleting the `list-element~1.json` file resolved this warning.

And since I have dealt with IDEs in the past that will save temporary files with the `~1` naming convention, I assumed this file was an accident that shouldn't have been in the repo. 

If you verify that I've come to the wrong conclusion and that the file is necessary, I will look at it further this evening to see which part of my thought process ^ was the big main misunderstanding, and maybe find a better way to resolve the PHP warnings.

2017-06-14 00:56 UTC, daggerhart commented
Verified that this was my misunderstanding and restored the file (PR updated).

For my own reference, this is a "pseudo pattern" - http://patternlab.io/docs/pattern-pseudo-patterns.html 

Not sure why I'm getting the PHP warning, but everything appears to work fine. Maybe we need to rename the file so that the pseudo-name is more than just "1"? Not too worried about it. Live and learn.

2017-06-14 00:59 UTC, nerdstein commented
We can certainly rename the variations if "1" is throwing a warning. I also get the warning but I ignored it because things seemed to "work". 

I'm going to merge this and we can resolve the error in a separate issue.

2017-06-14 00:59 UTC, merged